# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe8eac3269100cd6a7dd6e0e508288c7aac97e65a09640ef86d6346f4f5748cfca9dae8902e4a9e76405bc3da7147af2aea952716dc7d0203b7e7d95c24d97c4

test:
  secret_key_base: 34ceefa73650e06f6c4a5e7904e816d88f73663898f1fec706d93d8f12fd92b423581a1efc9461ee3626d7fa64493069a5c4b6783644855ea87f9a151a86df7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
